import React from 'react';
import ".././globals.css";
import NavigationBar from '../Components/UserLayout/NavigationBar/NavigationBar';
import Footer from '../Components/UserLayout/Footer/Footer';


export const metadata = {
  title: "Irony Fit",
  description: "Generated by Tamzid Ull Monir",
};

const HomeLayout = ({children}) => {
    return (
        <html lang="en">
        <body>
          <NavigationBar/>
          {children}
          <Footer/>
        </body>
      </html>
    );
};

export default HomeLayout;