import React from 'react';
import { Geist, Geist_Mono } from "next/font/google";
import ".././globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Irony Fit",
  description: "Generated by Tamzid Ull Monir",
};

const HomeLayout = ({children}) => {
    return (
        <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    );
};

export default HomeLayout;