import React from 'react';
import ".././globals.css";
import NavigationBar from '../Components/UserLayout/NavigationBar/NavigationBar';
import Footer from '../Components/UserLayout/Footer/Footer';


export const metadata = {
  title: "Irony Fit",
  description: "Generated by Tamzid Ull Monir",
};

const HomeLayout = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </head>
      <body>
        <NavigationBar />
        {children}
        <Footer />
      </body>
    </html>
  );
};

export default HomeLayout;